service: aws-nodejs 
provider:
 name: aws
 runtime: nodejs16.x
functions:
  OGScraper:
    handler: index.handler
    events:
      - http:
          path: parseOGData
          method: post
          cors: true
          request:
            schemas:
              application/json:
                schema: ${file(OGScraperPostRequestSchema.json)}
                name: OGScraperInputModel
                description: 'Validation model for OGScraper'
